version: 0.2
phases:
  pre_build:
    commands:
      - yarn install
      - cd workspaces/server
      - yarn install
      - cd ../../
  build:
    commands:
      - yarn build
artifacts:
  files:
    - "*"